name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <saifulislamadar@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  html: ^0.13.3+3
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.0.0
